# http://docs.travis-ci.com/user/languages/python/

language: python
python:
    - pypy
    - 3.8
    - 3.9
    - 3.10
#    - nightly # https://bugs.python.org/issue24934
    - pypy3

env:
    - DJANGO_VERSION=3.2

install:
    pip install django-bootstrap3 django-filer Django==$DJANGO_VERSION

script:
    python setup.py test

sudo: false
